SourceCode/DA_Framewrok/Controllers/ThongbaolopController.cs
using DA_Framewrok.Models;
using DA_Framewrok.Models.Authentication;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace DA_Framewrok.Controllers
{
    public class ThongbaolopController : Controller
    {
        TrungtamtienganhContext db = new TrungtamtienganhContext();
        [Authentication]
        public IActionResult Thongtinlop(int malophoc)
        {
            int maLopHoc = HttpContext.Session.GetInt32("SEMaLopHoc") ?? 0;

            var chitiet = db.Thongtinlophocs.Where(l => l.Malophoc == maLopHoc).Include(l=>l.MalophocNavigation).ToList();
            return View(chitiet);
        }
        [HttpGet]
        [Authentication]
        public IActionResult ThemThongBao()
        {
            return View();
        }
        [HttpPost]
        [Authentication]
        public IActionResult ThemThongBao(Thongtinlophoc thongbao, IFormFile? Tendinhkem) 
        {
            int maLopHoc = HttpContext.Session.GetInt32("SEMaLopHoc") ?? 0;

            DateOnly currentDate = DateOnly.FromDateTime(DateTime.Now);
            if (ModelState.IsValid)
            {
                if (Tendinhkem != null && Tendinhkem.Length > 0)
                {
                    string fileName = Path.GetFileName(Tendinhkem.FileName);
                    string uploadPath = Path.Combine("Upload", "Document");

                    // Đường dẫn lưu trữ trong wwwroot/Upload/Teacher
                    string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", uploadPath, fileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        Tendinhkem.CopyTo(stream);
                    }

                    thongbao.Tendinhkem = Path.Combine(uploadPath, fileName); // Lưu đường dẫn tương đối vào cơ sở dữ liệu
                }
                else
                {
                    thongbao.Tendinhkem = null;
                }

                int maxMathongbao = db.Thongtinlophocs.Max(h => (int?)h.Mathongtin) ?? 0;
                thongbao.Mathongtin = maxMathongbao + 1;
                thongbao.Ngaytao = currentDate;
                thongbao.Malophoc = maLopHoc;
                db.Thongtinlophocs.Add(thongbao);
                db.SaveChanges();
                TempData["SuccessMessage"] = "Bạn đã thêm thông báo thành công!";

                return RedirectToAction("Thongtinlop");
            }
            return View(thongbao);
        }
        [Authentication]
        public IActionResult Xoathongbao(int mathongtin)
        {
            db.Remove(db.Thongtinlophocs.Find(mathongtin));
            db.SaveChanges();
            TempData["SuccessDeleteMessage"] = "Bạn đã xóa thông tin thành công!";

            return RedirectToAction("Thongtinlop");
        }
    }
}

SourceCode/DA_Framewrok/Views/Thongbaolop/ThemThongBao.cshtml
@model DA_Framewrok.Models.Thongtinlophoc

@{
    ViewData["Title"] = "ThemThongBao";
    Layout = "~/Views/Shared/LayoutTeacher.cshtml";
}
<style>
    /* Tăng chiều cao cho CKEditor */
    .ck-editor__editable {
        min-height: 200px; /* Đặt chiều cao tối thiểu */
    }

    /* Tùy chỉnh chiều cao theo ý muốn */
    #editorNoidungthong,
    #editorTieude {
        min-height: 300px;
    }

</style>
<hr />
<div class="container py-3">
    <div class="row">
        <div class="col-12">
            <div class="bg-light rounded p-2">
                <ul class="nav nav-tabs">
                    <li class="nav-item ">
                        <a class="nav-link active" data-bs-toggle="tab" href="#all">Đang dạy</a>
                    </li>
                </ul>
                <div class="row">
                    <div class="col-12 py-2" style="margin-top: 35px;">
                        <div class="section-title">
                            <h1 class="display-6 fw-semibold text-center"> Thông tin chi tiết </h1>
                        </div>                       
                    </div>
                    <div class="container ps-5">
                        <div class="row">
                            <div class="col-md-12">
                                <form method="post" asp-action="ThemThongBao" enctype="multipart/form-data">
                                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                    <div class="form-group">
                                        <label asp-for="Tieude" class="control-label">Tiêu đề</label>
                                        <input asp-for="Tieude" class="form-control" ></input>
                                        <span asp-validation-for="Tieude" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Noidungthong" class="control-label">Nội dung</label>
                                        <textarea asp-for="Noidungthong" class="form-control" id="editorNoidungthong"></textarea>
                                        <span asp-validation-for="Noidungthong" class="text-danger"></span>
                                    </div>
                                    <div class="form-group">
                                        <label asp-for="Tendinhkem" class="control-label">File đính kèm(nếu có)</label>
                                        <input type="file" asp-for="Tendinhkem" class="form-control" />
                                        <span asp-validation-for="Tendinhkem" class="text-danger"></span>
                                    </div>

                                    <div class="form-group">
                                        <input type="submit" value="Create" class="btn btn-primary" />
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

<!-- Script để kích hoạt CKEditor cho các trường -->
<script>
    ClassicEditor
        .create(document.querySelector('#editorNoidungthong'))
        .catch(error => {
            console.error(error);
        });

    ClassicEditor
        .create(document.querySelector('#editorTieude'))
        .catch(error => {
            console.error(error);
        });
</script>

SourceCode/DA_Framewrok/Views/Thongbaolop/Thongtinlop.cshtml
@{
    ViewData["Title"] = "Thongtinlop";
    Layout = "~/Views/Shared/LayoutTeacher.cshtml";
}
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.15.1/css/all.css" integrity="sha384-kJ8U/JA6OQ+YJLxIsqZfL4c2DO8V/6aENZGnt2mi+2DZ++D9pFbBnP0EGaJG9SIf" crossorigin="anonymous">
<style>
    /* Add your custom styles here */
    body {
        background-color: #343a40;
        color: white;
    }

    .card {
        background-color: rgb(209, 209, 209);
        border-radius: 10px;
        padding: 20px;
        margin: 20px 0;
        position: relative; 
    }

    .card-title {
        font-size: 1.5rem;
        margin-bottom: 10px;
    }

    .card-text {
        font-size: 1rem;
        color: black;
        
    }

    .close-icon {
        position: absolute;
        top: 10px;
        right: 10px;
    }

    /* Add more styles as needed */
</style>
@model IEnumerable<DA_Framewrok.Models.Thongtinlophoc>

<div class="container py-3">
    <div class="row">
        <div class="col-12 py-3">
        </div>
        <div class="col-12">
            <div class="bg-light rounded p-2">
                <div class="row">
                    <div class="col-12 py-2" style="margin-top: 35px;">
                        <div class="section-title">
                            <h1 class="display-6 fw-semibold text-center"> Thông tin chi tiết </h1>
                        </div>
                        <a asp-controller="Thongbaolop" asp-action="Themthongbao" style="float: right;" class="rounded-3 btn btn-primary btn-lg">Thêm thông báo</a>
                    </div>
                    <div class="container ps-5">
                        <div class="row">
                            <div class="col-lg-12">

                                @if (TempData["SuccessDeleteMessage"] != null)
                                {
                                    <div class="alert alert-success">
                                        @TempData["SuccessDeleteMessage"]
                                    </div>
                                }
                                @foreach (var item in Model)
                                {
                                    <div class="card" style="overflow: hidden;">
                                        <a asp-controller="Thongbaolop" asp-action="Xoathongbao" asp-route-mathongtin="@item.Mathongtin" class="close-icon">
                                            <i class="fas fa-times btn btn-outline-primary"></i>
                                        </a>
                                        <h5 class="card-title" style="color: dodgerblue"><img style="width: 32px; height: 32px" src="~/css/notification(1).png" /> @Html.Raw(item.Tieude) </h5>
                                        <p class="card-text">* Ngày: @item.Ngaytao?.ToString("dd-MM-yyyy")</p>
                                        <div class="card-text">@Html.Raw(item.Noidungthong)</div>
                                        @if (item.Tendinhkem != null)
                                        {
                                            string filePath = item.Tendinhkem;
                                            string fileName = System.IO.Path.GetFileName(filePath);
                                            <a href="@Url.Content("~/" + item.Tendinhkem)">@fileName</a>
                                        }
                                    </div>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>